name: Feature request
description: "Suggest an idea for Thalwyrn"
title: "[FEAT] YOUR-FEATURE-TITLE-HERE"
labels: [enhancement]
# assignees: []

body:
- type: textarea
  attributes:
    label: Problem Description
    description: Provide a brief and concise explanation of the problem. For example, mention the frustration caused by...

- type: textarea
  validations:
    required: true
  attributes:
    label: Desired Solution
    description: Provide a brief and concise description of the expected outcome.


- type: textarea
  attributes:
    label: Alternatives Considered
    description: Briefly describe any other potential solutions or features you have thought of.

- type: textarea
  attributes:
    label: Additional Context
    description: Include any relevant context or attach screenshots related to your feature request here.```
